Repository cloudwalk/brlc-capybara-finance, pull requests merged in 2025-09, with the labels that each got.

#92 chore: dev-ex improvements
  .eslintrc.json
  .github/workflows/branch.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  .gitignore
  .husky/pre-commit
  .mocharc.json
  .prettierrc
  README.md
  contracts/CreditLine.sol
  contracts/LendingMarket.sol
  contracts/LiquidityPool.sol
  contracts/base/Versionable.sol
  eslint.config.js
  hardhat.config.ts
  package-lock.json
  package.json
  scripts/deployProxy.ts
  scripts/prepareUpgrade.ts
  scripts/upgradeProxy.ts
  scripts/validateUpgrade.ts
  test-utils/common.ts
  test-utils/eth.ts
  test-utils/specific.ts
  test/CreditLine.test.ts
  test/LendingMarket.base.test.ts
  test/LendingMarket.complex.test.ts
  test/LiquidityPool.test.ts
  test/base/AccessControlExtUpgradeable.test.ts
  test/base/PausableExtUpgradeable.test.ts
  test/libraries/ABDKMath64x64.test.ts
  test/libraries/Rounding.test.ts
  tsconfig.json
Labels: maintenance

#95 build: contracts upgrade
  .openzeppelin/unknown-2008.json
  .openzeppelin/unknown-2009.json
  package-lock.json
Labels: deploy-upgrade

#97 feat: introduce the loan correction functionality
  .env.example
  contracts/LendingMarket.sol
  contracts/base/Versionable.sol
  contracts/interfaces/ILendingMarket.sol
  test-utils/specific.ts
  test/LendingMarket.base.test.ts
Labels: enhancement
